# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Update project dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ../var/www/it-geto
            rm -rf .env
            git reset --hard
            git pull

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_PORT: ${{ secrets.APP_PORT }}

          envkey_MONGO_URL: ${{ secrets.APP_MONGO_URL }}

          envkey_REDIS_HOST: ${{ secrets.APP_REDIS_HOST }}
          envkey_REDIS_PORT: ${{ secrets.APP_REDIS_PORT }}

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          source: ".env"
          target: "../var/www/it-geto"

      - name: Build the project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ../var/www/it-geto
            
            echo "Building project"
            
            npm i
            npm run build
            npm run restart
            
            echo "Update nginx"
            
            cp -fr nginx.conf /../../../etc/nginx/conf.d/it-square.conf
            sed -i "s/%PORT%/${{ secrets.APP_PORT }}/" /../../../etc/nginx/conf.d/it-geto.conf
            sed -i "s/%DOMAIN%/${{ secrets.APP_DOMAIN }}/" /../../../etc/nginx/conf.d/it-geto.conf
            
            nginx -s reload
